name: Deploy to EC2 Instances

on:
  push:
    branches: [ master, Development ]
  pull_request:
    branches: [ master, Development ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r Computex/requirements.txt

    - name: Run backend tests
      env:
        DJANGO_SETTINGS_MODULE: Computex.test_settings
      run: |
        cd Computex
        python manage.py test

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      run: |
        cd ComputexFrontend
        npm install

    - name: Build frontend
      run: |
        cd ComputexFrontend
        npm run build

    - name: Deploy to EC2 instances
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        FRONTEND_HOST: ${{ secrets.FRONTEND_HOST }}
        BACKEND_HOST: ${{ secrets.BACKEND_HOST }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -r ComputexFrontend/dist/* ubuntu@$FRONTEND_HOST:/home/ubuntu/frontend
        scp -i private_key -o StrictHostKeyChecking=no -r Computex/* ubuntu@$BACKEND_HOST:/home/ubuntu/backend
        scp -i private_key -o StrictHostKeyChecking=no requirements.txt ubuntu@$BACKEND_HOST:/home/ubuntu/backend/
        ssh -i private_key -o StrictHostKeyChecking=no ubuntu@$BACKEND_HOST '
          cd /home/ubuntu/backend &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          python manage.py migrate &&
          sudo systemctl restart gunicorn
        '
        ssh -i private_key -o StrictHostKeyChecking=no ubuntu@$FRONTEND_HOST 'sudo systemctl restart nginx'