name: CI/CD Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  

    - name: Update kubeconfig
      run: aws eks get-token --cluster-name computex-cluster | kubectl apply -f -

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/computex-frontend computex-frontend=mrkaykab/computex-frontend:latest
        kubectl set image deployment/computex-backend computex-backend=mrkaykab/computex-backend:latest
