name: CI/CD Pipeline

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Update if the cluster is in a different region

    - name: Check if EKS cluster exists (debugging step)
      run: |
        echo "Listing available EKS clusters in the region..."
        aws eks list-clusters --region us-east-1
        echo "Checking if the cluster exists..."
        aws eks describe-cluster --name computex-cluster --region us-east-1

    - name: Configure kubectl with EKS
      run: |
        aws eks --region us-east-1 update-kubeconfig --name computex-cluster
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/computex-frontend computex-frontend=mrkaykab/computex-frontend:latest
        kubectl set image deployment/computex-backend computex-backend=mrkaykab/computex-backend:latest
