name: CI/CD Pipeline

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install eksctl
      run: |
        curl -s --location "https://github.com/weaveworks/eksctl/releases/download/v0.154.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Configure kubectl
      run: |
        aws eks --region us-east-1 update-kubeconfig --name computex-cluster
        kubectl get nodes

    - name: Apply Kubernetes deployments (frontend and backend)
      run: |
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f backend-deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/computex-frontend computex-frontend=mrkaykab/computex-frontend:latest
        kubectl set image deployment/computex-backend computex-backend=mrkaykab/computex-backend:latest
