name: CI/CD Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Frontend Docker image
      env:
        DOCKER_REPO: your-dockerhub-username/computex-frontend
      run: |
        docker build -t $DOCKER_REPO:${{ github.sha }} frontend/
        docker push $DOCKER_REPO:${{ github.sha }}
    
    - name: Build and push Backend Docker image
      env:
        DOCKER_REPO: your-dockerhub-username/computex-backend
      run: |
        docker build -t $DOCKER_REPO:${{ github.sha }} backend/
        docker push $DOCKER_REPO:${{ github.sha }}
    
    - name: Update kubeconfig
      run: aws eks get-token --cluster-name computex-cluster | kubectl apply -f -

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/computex-frontend computex-frontend=your-dockerhub-username/computex-frontend:${{ github.sha }}
        kubectl set image deployment/computex-backend computex-backend=your-dockerhub-username/computex-backend:${{ github.sha }}
